package br.com.cpqd.avm.sdk.v1.utils;

public interface SdkConstantsExceptions {

	public interface Builder {

		String EXCEPTION__DATA_MODEL_MENU__CONTENT = "SDK-0301";
		String EXCEPTION__REQUEST_AVM__REQUEST_ID = "SDK-0302";
		String EXCEPTION__REQUEST_AVM__ACTION = "SDK-0303";
		String EXCEPTION__RESPONSE_AVM__STATUS = "SDK-0304";
		String EXCEPTION__RESPONSE_AVM__REQUEST_ID = "SDK-0305";
		String EXCEPTION__RESPONSE_FAILED_AVM__CODE = "SDK-0306";
		String EXCEPTION__RESPONSE_FAILED_AVM__MESSAGE = "SDK-0307";
		String EXCEPTION__RESPONSE_SUCCESS_AVM__STATUS = "SDK-0308";
		String EXCEPTION__RESPONSE_SUCCESS_AVM__ERROR_CODE = "SDK-0309";
		String EXCEPTION__RESPONSE_SUCCESS_AVM__ERROR_CODE__NOT_REQUIRED = "SDK-0310";
		String EXCEPTION__RESPONSE_SUCCESS_AVM__ERROR_MESSAGE = "SDK-0311";
		String EXCEPTION__RESPONSE_SUCCESS_AVM__ERROR_MESSAGE__NOT_REQUIRED = "SDK-0312";
		String EXCEPTION__RESPONSE_SUCCESS_AVM__RESPONSE = "SDK-0313";
		String EXCEPTION__RESPONSE_SUCCESS_AVM__EVENT_NAME = "SDK-0314";
		String EXCEPTION__RESPONSE_SUCCESS_AVM__TYPE = "SDK-0315";
		String EXCEPTION__RESPONSE_FAILED_AVM__REQUEST_ID = "SDK-0316";
		String EXCEPTION__RESPONSE_SUCCESS_AVM__REQUEST_ID = "SDK-0317";
		
	}

}
