package br.com.cpqd.avm.sdk.v1.utils;

public interface SdkConstantsExceptions {

	public String EXCEPTION_RESPONSE = "SDK-0000";
	public String EXCEPTION_RESPONSE_STATUS = "SDK-0001";
	public String EXCEPTION_RESPONSE_REQUEST_ID = "SDK-0002";
	public String EXCEPTION_RESPONSE_CODE = "SDK-0003";
	public String EXCEPTION_RESPONSE_MESSAGE = "SDK-0004";
	public String EXCEPTION_RESPONSE_RESPONSE = "SDK-0005";

	public String EXCEPTION_RESPONSE_RESPONSE_EVENT_NAME = "SDK-0006";
	public String EXCEPTION_RESPONSE_RESPONSE_STATUS = "SDK-0007";
	public String EXCEPTION_RESPONSE_RESPONSE_ERROR_CODE = "SDK-0008";
	public String EXCEPTION_RESPONSE_RESPONSE_ERROR_MESSAGE = "SDK-0009";
	public String EXCEPTION_RESPONSE_RESPONSE_RESPONSE = "SDK-0010";
	public String EXCEPTION_RESPONSE_RESPONSE_ERROR_CODE_NOT_NECESSARY = "SDK-0011";
	public String EXCEPTION_RESPONSE_RESPONSE_ERROR_MESSAGE_NOT_NECESSARY = "SDK-0012";
	public String EXCEPTION_RESPONSE_RESPONSE_TYPE = "SDK-0013";

	public String EXCEPTION_REQUEST = "SDK-0100";
	public String EXCEPTION_REQUEST_REQUEST_ID = "SDK-0101";
	public String EXCEPTION_REQUEST_ACTION = "SDK-0102";

	public String EXCEPTION_DATA_MODEL = "SDK-0200";
	public String EXCEPTION_DATA_MODEL_MENU = "SDK-0201";
	public String EXCEPTION_DATA_MODEL_MENU_CONTENT = "SDK-0202";

	public String EXCEPTION_DATA_MODEL_CONTENT = "SDK-0101";

	public String EXCEPTION_UNKNOW = "SDK-1000";

}
